version: "3.3"

services:
  app: 
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.2-alpine
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app